In [1]:
import numpy as np
import pandas as pd
import random
import math
import matplotlib.pyplot as plt

In [77]:
class ANN():
    h = None # num of hidden layers
    s = None # num of units in hidden layer
    k = None # num of class
    weights = None
    def __init__(self,h,s):
        self.h = h #num of hidden layer
        self.s = s #num of nodes in each hidden layer
        self.k = 10
    # X is m*n matrix, y is m*1 vector, alpha is training parameter
    #t is number of iterations
    def fit(self,X,y,alpha,t):
        Cost = []
        m = X.shape[0] #number of examples
        n = X.shape[1] #number of features
        #Xavier Initialization
        self.weights = [] #length h+1
        self.weights.append(np.random.uniform(low=-math.sqrt(6/(n+self.s)), high=math.sqrt(6/(n+1+self.s)), size=(self.s, n+1)))
        for i in range(self.h-1):
            self.weights.append(np.random.uniform(low=-math.sqrt(6/(2*self.s)), high=math.sqrt(6/(2*self.s)), size=(self.s, self.s+1)))
        if len(set(y))==2:
            self.k = 1
        elif len(set(y))>=3:
            self.k = len(set(y))
        else:
            print("cannot have less than 2 classes")
            return
        self.k = 10
        Y = np.array([[0]*self.k]*m)
        for i in range(m):
            Y[i][y[i]]=1
        self.weights.append(np.random.uniform(low=-math.sqrt(6/(self.k+self.s)), high=math.sqrt(6/(self.k+self.s)), size=(self.k, self.s+1)))
        for it in range(t):
            for row in range(m):
                #change the form of y value in an example from integer to array
                a = [] #list of matrices of input in each layer
                currA = [1] #input layer, add bias term
                for i in range(X.shape[1]): #iterate all columns in an example
                    currA.append(X.iloc[row][i])
                a.append(np.array(currA))
                input = [] # Store input in each layer
                input.append(currA[1:])
                for l in range(self.h+1):
                    input.append(np.matmul(self.weights[l],currA))
                    currA = sigmoid(input[l+1])
                    currA = np.hstack([[1],currA]) #add bias term in current a
                    a.append(currA)
                delta = []
                delta.append(np.multiply(sigmoidPrime(a[self.h+1][1:]),Y[row]-a[self.h+1][1:,]))
                #print(delta[0].shape[0])
                for l in range(self.h,-1,-1):
                    sum = np.matmul(self.weights[l].transpose(),delta[0])[1:,]
                    delta.insert(0,np.multiply(sigmoidPrime(a[l][1:]),sum))
                for l in range(self.h+1):
                    self.weights[l] = self.weights[l] + alpha*np.outer(delta[l+1],a[l])
                ypred = self.predict(X)  # q * k
                Loss = np.mean((Y-ypred)**2)/2
                print(Loss)
        plt.plot(range(l),Cost)
        plt.show()
    def predict(self,T):
        ypred = []
        m = T.shape[0]
        for row in range(m):
            a = [1] #input layer, add bias term
            for i in range(T.shape[1]):
                a.append(T.iloc[row][i])
            a = np.array(a)
            for l in range(self.h+1):
                input = np.matmul(self.weights[l],a)
                a = sigmoid(input)
                a = np.hstack([[1],a]) # add bias term
            ypred.append(a[1:,])
        return np.array(ypred) # return a numpy array
    def print(self):
        for l in range(self.weights.shape[0]):
            print("Weights of Layer "+str(l))
            printWeight(self.weights[l].transpose())

def sigmoid(input):
    return 1/(1+np.exp(-input))
def sigmoidPrime(input):
    #return np.multiply(input,1-input)
    return input*(1-input)

def printWeight(weight):
    for i in range(weight.shape[0]):
        for j in range(weight.shape[1]):
            print(weight[i,j],end = " ")
        print("")

In [78]:
#read MNIST data
size = 400
data = pd.read_csv("train.csv").iloc[:size]
X = data.drop("label",1)
y = data["label"]
h = 1
s = 3
alpha = 0.01
t = 1
model = ANN(h,s)
model.fit(X,y,alpha,t)

0.134345728341
0.134067221362
0.133781661724
0.13437763654
0.134096625052
0.133816386158
0.132680585624
0.13241591762
0.132193474076
0.131886323494
0.131638849207
0.131366859713
0.131138169765
0.130870823828


KeyboardInterrupt: 

In [ ]:
np.matrix([1,2,3])[0].dot(np.matrix([2,3,4])[0])

In [17]:
np.matrix([1,2,3])*np.matrix([2,3,4])

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [82]:
weights = [] #length h+1
np.array([-1.14282988,])

[array([[-1.00242868, -0.79096395, -0.42700726],
        [ 0.89656211, -0.389382  ,  1.07474137]])]

In [83]:
a = [1,2,3,4]

In [84]:
b = [3,4,5,6]

In [85]:
c = []

In [86]:
c.append(a)

In [87]:
c.append(b)

In [88]:
c = np.array(c)

In [89]:
c

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [90]:
c[:,0]

array([1, 3])

In [93]:
mean = np.mean(c,0)

In [94]:
mean

array([ 2.,  3.,  4.,  5.])

In [95]:
for col in range(4):
    c[:, col] = c[:, col] - mean[col]

In [96]:
c

array([[-1, -1, -1, -1],
       [ 1,  1,  1,  1]])